import { GridColDef, GridRenderCellParams } from "@mui/x-data-grid"
import { NUMBERMAP } from "./skill";

export const TRAINING_EVALUATION_BASE_PATH = 'api/v1/hrcs/training-evaluation';
export const TRAINING_SCHEDULE_BASE_PATH = 'api/v1/hrcs/training-schedule';

export const API_ENDPOINTS = {
  EVALUATION: {
    FETCH_ALL: `${TRAINING_EVALUATION_BASE_PATH}/all?status=${NUMBERMAP.ONE}`,
    FETCH_BY_ID: (id: string) => `${TRAINING_EVALUATION_BASE_PATH}/${id}`,
    FETCH_TRAINING_SCHEDULE: `${TRAINING_SCHEDULE_BASE_PATH}/all`,
    FETCH_TRAINING_SCHEDULE_BY_ID: (id: string) => `${TRAINING_SCHEDULE_BASE_PATH}/${id}`,
    FETCH_TRAINING_EVALUATION_BY_ID: (id: string) => `${TRAINING_EVALUATION_BASE_PATH}/${id}`,
    FETCH_SKILL: 'api/v1/hrcs/skill-level/all'  
  },
}

// String literals from the page files
export const STRING_LITERALS = {
  // Form field names
  EVALUATION_DATE: 'evaluationDate',
  SELECTED_TRAINING_ID: 'selectedTrainingId',
  LEVEL_REQUIRED: 'levelRequired',
  LEVEL_ACQUIRED: 'levelAcquired',
  METHOD_OF_EVALUATION: 'methodOfEvaluation',
  REMARKS: 'remarks',
  SELECTED_SKILL: 'selectedSkill',
  MODE_OF_TRAINING: 'mode_of_training',
  
  // Empty strings
  EMPTY_STRING: '',
  
  // Default values
  DEFAULT_DASH: '-',
  DEFAULT_EMPTY: '',
  
  // Comments
  ADDITIONAL_CONTROLS_COMMENT: 'Add any additional controls or buttons here',
  HIDDEN_INPUTS_COMMENT: 'Hidden inputs for all skills for magicFormSave',
  
  // CSS classes and styles
  EXPANDED_ROW_BACKGROUND: '#f5f5f5',
  DISPLAY_NONE: 'none',
  ELLIPSIS: '...',
  
  // Template literals
  EDIT_PREFIX: 'edit-',
  SKILL_PREFIX: 'skill-',
  ROW_SKILL_TEMPLATE: (rowId: string, skillId: string, idx: number) => `${rowId}-skill-${skillId}-${idx}`,
  ROW_INDEX_TEMPLATE: (rowId: string, index: number) => `${rowId}-${index}`,
  SKILL_INDEX_TEMPLATE: (rowDataId: string, skillIdx: number) => `${rowDataId}-${skillIdx}`,
  
  // CSS class names
  EXPANDABLE_ROW_CLASS: 'expandable-row',
  EXPANDED_ROW_CLASS: 'expanded-row',
  HIDDEN_INPUTS_CLASS: 'hidden-inputs',
  TABLE_CONTAINER_CLASS: 'table-container',
  SKILL_ROW_CLASS: 'skill-row',
  
  // Style values
  CURSOR_POINTER: 'pointer',
  TEXT_DECORATION_UNDERLINE: 'underline',
  DISPLAY_FLEX: 'flex',
  FLEX_DIRECTION_COLUMN: 'column',
  WIDTH_100: '100%',
  
  // Field names for hidden inputs
  FK_EQMS_HR_TRAINING_ATTENDEE_ID: 'fk_eqms_hr_training_attendee_id',
  FK_EQMS_HR_SKILL_MASTER_ID: 'fk_eqms_hr_skill_master_id',
  FK_EQMS_HR_REQUIRED_SKILL_LEVEL_ID: 'fk_eqms_hr_required_skill_level_id',
  FK_EQMS_HR_ACQUIRED_SKILL_LEVEL_ID: 'fk_eqms_hr_acquired_skill_level_id',
  METHOD_OF_EVALUATION_FIELD: 'method_of_evaluation',
  REMARKS_FIELD: 'remarks',
  
  // Container IDs
  MODAL_CONTAINER_ID: 'HR_TRAINING_EVALUATION_EVALUATION_DETAILS',
  
  // File handling
  FILE_ID: 'file_id',
  ID: 'id',
  SKILL_ID: 'skill_id',
  
  // Skill column fields
  SNO: 'sno',
  SKILL_SKILL_NAME: 'skill_name',
  SKILL_LEVEL_REQUIRED: 'levelRequired',
  SKILL_LEVEL_ACQUIRED: 'levelAcquired',
  SKILL_METHOD_OF_EVALUATION: 'methodOfEvaluation',
  SKILL_REMARKS: 'remarks',
  SKILL_ACTION: 'action',
  
  // Skill column headers
  SKILL_SNO_HEADER: 'S.No',
  SKILL_SKILLS_IMPARTED: 'Skills Imparted',
  SKILL_LEVEL_ACQUIRED_HEADER: 'Level Aquired',
  SKILL_LEVEL_REQUIRED_HEADER: 'Level Required',
  SKILL_METHOD_OF_EVALUATION_HEADER: 'Method of Evaluation',
  SKILL_REF_OF_EVALUATION: 'Ref of Evaluation / Remarks',
  SKILL_ACTION_HEADER: 'Action',
  
  // Table field names
  FIRST_NAME: 'first_name',
  LAST_NAME: 'last_name',
  ROLE_NAME: 'role_name',
  DEPARTMENT_NAME: 'department_name',
  STATUS: 'status',
  SKILLS: 'skills',
  HR_ATTENDEE_ID: 'hr_attendee_id',
  
  // Table header names
  S_NO: 'S.No',
  NAME: 'Name',
  ROLE: 'Role',
  DEPARTMENT: 'Department',
  STATUS_HEADER: 'Status',
  EVALUATION: 'Evaluation',
  
  // Table header constants
  TABLE_HEADER_SNO: 'S.No',
  TABLE_HEADER_NAME: 'Name',
  TABLE_HEADER_ROLE: 'Role',
  TABLE_HEADER_DEPARTMENT: 'Department',
  TABLE_HEADER_STATUS: 'Status',
  TABLE_HEADER_EVALUATION_DETAILS: 'Evaluation Details',
  
  // No data message
  NO_RECORD_FOUND: 'No Records Found...',
  
  // Data source and field names
  EQMS_HR_TRAINING_EVALUATION: 'eqms_hr_training_evaluation',
  EQMS_HR_EMPLOYEE_TRAINING_EVALUATION: 'eqms_hr_employee_training_evaluation',
  FK_EQMS_HR_TRAINING_EVALUATION_ID: 'fk_eqms_hr_training_evaluation_id',
  FK_EQMS_HR_TRAINING_SCHEDULE_ID: 'fk_eqms_hr_training_schedule_id',
  FK_EQMS_HR_TRAINING_ATTENDEE_ID_FIELD: 'fk_eqms_hr_training_attendee_id',
  FK_EQMS_HR_SKILL_MASTER_ID_FIELD: 'fk_eqms_hr_skill_master_id',
  FK_EQMS_HR_REQUIRED_SKILL_LEVEL_ID_FIELD: 'fk_eqms_hr_required_skill_level_id',
  FK_EQMS_HR_ACQUIRED_SKILL_LEVEL_ID_FIELD: 'fk_eqms_hr_acquired_skill_level_id',
  METHOD_OF_EVALUATION_FIELD_NAME: 'method_of_evaluation',
  REMARK_FIELD: 'remarks',
  STATUS_FIELD: 'status',
  
  // Values
  CREATE: 'create',
  UPDATE: 'update',
  INSERT: 'insert',
  RESPONSE: 'response',
  SAVE: 'Save',
  CANCEL: 'Cancel',
  PATH: '/hr/training-evaluation',
  DATE_FORMAT: 'YYYY-MM-DDTHH:mm:ss.000[Z]',
  SUCCESS: 'success',
  FAILED: 'failed',
  TEXT: 'text',
  TRUE: 'true',
  
  // Training evaluation list
  TRAINING_EVALUATION_TITLE: 'Training Evaluation',
  TRAINING_EVALUATION_ID_FIELD: 'training_evaluation_id',
  TRAINING_EVALUATION_PLACEHOLDER: 'Enter title of training',
  TRAINING_EVALUATION_DATE_OF_EVALUATION: 'Date of Evaluation*',
  TRAINING_EVALUATION_ATTENDEES: 'Attendees',
  TRAINING_EVALUATION_EVALUATION_DETAILS: 'Evaluation Details',
  TRAINING_EVALUATION_SKILL_IMPORTED: 'Skill Imparted',
  
  // Labels
  LEVEL_REQUIRED_LABEL: 'Level Required',
  SELECT_LEVEL_LABEL: 'Please Select level',
  LEVEL_ACQUIRED_LABEL: 'Level Acquired',
  EVALUATION_LABEL: 'Method of Evaluation',
  EVALUATION_PLACEHOLDER_LABEL: 'Enter Method of Evaluation',
  REMARKS_LABEL: 'Evaluation/Remarks',
  REMARKS_PLACEHOLDER_LABEL: 'Enter Evaluation/Remarks',
  
  // Titles
  TITLE_OF_TRAINING: 'Title of Training*',
  TITLE_MODE_OF_TRAINING: 'Mode of Training',
  
  // Other constants
  TRAINING_EVALUATION_CONST: 'training evaluations',
  TRAINING_EVALUATION_BY_ID: 'training evaluation',
  TRAINING_SCHEDULE: 'training schedules',
  TRAINING_SCHEDULE_BY_ID: 'training_schedule_id',
  TRAINING_EVALUATION_FETCH_BY_ID: 'training_evaluation_fetch_by_id',
  SKILLS_CONST: 'SKILLS',
  DATA_DELETE: 'data-grid-delete row-',
  PATHNAME: '/hr/training-evaluation/create',
  TRAINING_EVALUATION_ID: 'training_evaluation_id',
  TITLE_CONST: 'title',
  EVALUATION_DATE_CONST: 'evaluation_date',
  TITLE_EVALUATION_DATE: 'Evaluation Date',
  TRAINER: 'fullName',
  NAME_OF_TRAINER: 'Name of Trainer',
  MODE_OF_TRAINING_CONST: 'mode_of_training',
  ACTION: 'action',
  TITLE_ACTION: 'Action',
  HR_TRAINING_EVALUATION: 'HR_TRAINING_EVALUATION',
  ID_CONST: 'id',
  DATA_GRID_DELETE_CLASS: '.data-grid-delete',
  CONTAINER_ID: 'HR_TRAINING_EVALUATION',
  DATA_SOURCE_NAME: 'eqms_hr_training_evaluation',
  DATA_FIELD_NAME: 'status',
  FILE_SECTION_TABLES: 'eqms_hr_employee_training_evaluation_supporting_files',
  SUPPORTING_FILE: 'supporting_files',
  TITLE_OF_TRAINING_HEADER: 'Title of Training',
  
  // Template string patterns
  EDIT_ID_PATTERN: (attendeeId: number) => `edit-${attendeeId}`,
  ROW_ID_PATTERN: (itemId: number, attendeeId: number) => `${itemId}-${attendeeId}`,
  SKILL_ROW_ID_PATTERN: (rowId: string | number, skillIdx: number) => `${rowId}-${skillIdx}`,
  HIDDEN_INPUT_KEY_PATTERN: (rowId: string | number, skillId: number, attendeeId: number) => `${rowId}-skill-${skillId}-${attendeeId}`,
  CELL_KEY_PATTERN: (rowId: string | number, field: string) => `${rowId}-${field}`,
  
  // Status labels
  STATUS_VALID: 'Active',
  STATUS_INVALID: 'Inactive',
} as const;

export const TRAINING_EVALUATION = STRING_LITERALS.TRAINING_EVALUATION_CONST;
export const TRAINING_EVALUATION_BY_ID = STRING_LITERALS.TRAINING_EVALUATION_BY_ID;
export const TRAINING_SCHEDULE = STRING_LITERALS.TRAINING_SCHEDULE;
export const TRAINING_SCHEDULE_BY_ID = STRING_LITERALS.TRAINING_SCHEDULE_BY_ID;
export const TRAINING_EVALUATION_FETCH_BY_ID = STRING_LITERALS.TRAINING_EVALUATION_FETCH_BY_ID;
export const SKILLS = STRING_LITERALS.SKILLS_CONST;
export const DATA_DELETE = STRING_LITERALS.DATA_DELETE;
export const PATHNAME = STRING_LITERALS.PATHNAME;
export const TRAINING_EVALUATION_ID = STRING_LITERALS.TRAINING_EVALUATION_ID;
export const S_NO = STRING_LITERALS.S_NO;
export const TITLE = STRING_LITERALS.TITLE_CONST;
export const TITLE_OF_TRAINING = STRING_LITERALS.TITLE_OF_TRAINING;
export const EVALUATION_DATE = STRING_LITERALS.EVALUATION_DATE_CONST;
export const TITLE_EVALUATION_DATE = STRING_LITERALS.TITLE_EVALUATION_DATE;
export const TRAINER = STRING_LITERALS.TRAINER;
export const NAME_OF_TRAINER = STRING_LITERALS.NAME_OF_TRAINER;
export const MODE_OF_TRAINING = STRING_LITERALS.MODE_OF_TRAINING_CONST;
export const TITLE_MODE_OF_TRAINING = STRING_LITERALS.TITLE_MODE_OF_TRAINING;
export const ACTION = STRING_LITERALS.ACTION;
export const TITLE_ACTION = STRING_LITERALS.TITLE_ACTION;
export const HR_TRAINING_EVALUATION = STRING_LITERALS.HR_TRAINING_EVALUATION;
export const ID = STRING_LITERALS.ID_CONST;
export const TEXT = STRING_LITERALS.TEXT;


export const TRAINING_EVALUATION_LIST = {
  TITLE: STRING_LITERALS.TRAINING_EVALUATION_TITLE,
  ID_FIELD: STRING_LITERALS.TRAINING_EVALUATION_ID_FIELD,
  PLACEHOLDER: STRING_LITERALS.TRAINING_EVALUATION_PLACEHOLDER,
  DATE_OF_EVALUATION: STRING_LITERALS.TRAINING_EVALUATION_DATE_OF_EVALUATION,
  ATTENDEES: STRING_LITERALS.TRAINING_EVALUATION_ATTENDEES,
  EVALUATION_DETAILS: STRING_LITERALS.TRAINING_EVALUATION_EVALUATION_DETAILS,
  SKILL_IMPORTED: STRING_LITERALS.TRAINING_EVALUATION_SKILL_IMPORTED,
}

export const LABEL = {
  LEVEL_REQUIRED: STRING_LITERALS.LEVEL_REQUIRED_LABEL,
  SELECT_LEVEL: STRING_LITERALS.SELECT_LEVEL_LABEL,
  LEVEL_ACQUIRED: STRING_LITERALS.LEVEL_ACQUIRED_LABEL,
  EVALUATION: STRING_LITERALS.EVALUATION_LABEL,
  EVALUATION_PLACEHOLDER: STRING_LITERALS.EVALUATION_PLACEHOLDER_LABEL,
  REMARKS: STRING_LITERALS.REMARKS_LABEL,
  REMARKS_PLACEHOLDER: STRING_LITERALS.REMARKS_PLACEHOLDER_LABEL,
}

export const getSkillColumns = (
  renderActionCell: (params: GridRenderCellParams) => React.ReactNode,
): GridColDef[] => [
    { field: STRING_LITERALS.SNO, headerName: STRING_LITERALS.SKILL_SNO_HEADER},
    { field: STRING_LITERALS.SKILL_SKILL_NAME, headerName: STRING_LITERALS.SKILL_SKILLS_IMPARTED,flex:NUMBERMAP.ONE },
    { field: STRING_LITERALS.SKILL_LEVEL_REQUIRED, headerName: STRING_LITERALS.SKILL_LEVEL_REQUIRED_HEADER,flex:NUMBERMAP.ONE },
    { field: STRING_LITERALS.SKILL_LEVEL_ACQUIRED, headerName: STRING_LITERALS.SKILL_LEVEL_ACQUIRED_HEADER,flex:NUMBERMAP.ONE },
    { field: STRING_LITERALS.SKILL_METHOD_OF_EVALUATION, headerName: STRING_LITERALS.SKILL_METHOD_OF_EVALUATION_HEADER,flex:NUMBERMAP.ONE },
    { field: STRING_LITERALS.SKILL_REMARKS, headerName: STRING_LITERALS.SKILL_REF_OF_EVALUATION,flex:NUMBERMAP.ONE },
    {
      field: STRING_LITERALS.SKILL_ACTION,
      headerName: STRING_LITERALS.SKILL_ACTION_HEADER,
      renderCell: renderActionCell,
    },
  ];

export const VALUE_FIELD = {
  SKILL_ID: STRING_LITERALS.SKILL_ID,
  LEVEL_REQUIRED: STRING_LITERALS.LEVEL_REQUIRED,
  LEVEL_ACQUIRED: STRING_LITERALS.LEVEL_ACQUIRED,
  METHOD_OF_EVALUATION: STRING_LITERALS.METHOD_OF_EVALUATION,
  REMARK: STRING_LITERALS.REMARKS,
  SELECTED_SKILL: STRING_LITERALS.SELECTED_SKILL,
  SELECTED_TRAINING_ID: STRING_LITERALS.SELECTED_TRAINING_ID,
  EVALUATION_DATE: 'evaluationDate'
} as const 

export const VALUE = {
 
  SAVE: STRING_LITERALS.SAVE,
  CANCEL: STRING_LITERALS.CANCEL
} as const

export const FIELD_NAME = {
  S_NO: STRING_LITERALS.SNO,
  FIRST_NAME: STRING_LITERALS.FIRST_NAME,
  ROLE_NAME: STRING_LITERALS.ROLE_NAME,
  DEPARTMENT_NAME: STRING_LITERALS.DEPARTMENT_NAME,
  STATUS: STRING_LITERALS.STATUS,
  SKILLS: STRING_LITERALS.SKILLS,
  HR_ATTENDEE_ID: STRING_LITERALS.HR_ATTENDEE_ID
} as const 

export const HEADER_NAME = {
  S_NO: STRING_LITERALS.S_NO,
  NAME: STRING_LITERALS.NAME,
  ROLE: STRING_LITERALS.ROLE,
  DEPARTMENT: STRING_LITERALS.DEPARTMENT,
  STATUS: STRING_LITERALS.STATUS_HEADER,
  EVALUATION: STRING_LITERALS.EVALUATION,
} as const 

export const DATA_GRID_DELETE_CLASS = STRING_LITERALS.DATA_GRID_DELETE_CLASS;
export const CONTAINER_ID = STRING_LITERALS.CONTAINER_ID;
export const DATA_SOURCE_NAME = STRING_LITERALS.DATA_SOURCE_NAME;
export const DATA_FIELD_NAME = STRING_LITERALS.DATA_FIELD_NAME;
export const FILE_SECTION_TABLES = STRING_LITERALS.FILE_SECTION_TABLES;
export const SUPPORTING_FILE = STRING_LITERALS.SUPPORTING_FILE;

export const DEFAULT_DASH = STRING_LITERALS.DEFAULT_DASH;
export const ELLIPSIS = STRING_LITERALS.ELLIPSIS;
export const EXPANDABLE_ROW_CLASS = STRING_LITERALS.EXPANDABLE_ROW_CLASS;
export const EXPANDED_ROW_CLASS = STRING_LITERALS.EXPANDED_ROW_CLASS;
export const HIDDEN_INPUTS_CLASS = STRING_LITERALS.HIDDEN_INPUTS_CLASS;
export const TABLE_CONTAINER_CLASS = STRING_LITERALS.TABLE_CONTAINER_CLASS;
export const SKILL_ROW_CLASS = STRING_LITERALS.SKILL_ROW_CLASS;
export const CURSOR_POINTER = STRING_LITERALS.CURSOR_POINTER;
export const TEXT_DECORATION_UNDERLINE = STRING_LITERALS.TEXT_DECORATION_UNDERLINE;
export const DISPLAY_FLEX = STRING_LITERALS.DISPLAY_FLEX;
export const FLEX_DIRECTION_COLUMN = STRING_LITERALS.FLEX_DIRECTION_COLUMN;
export const WIDTH_100 = STRING_LITERALS.WIDTH_100;

export const MODAL_CONTAINER_ID = STRING_LITERALS.MODAL_CONTAINER_ID;
export const FK_EQMS_HR_TRAINING_ATTENDEE_ID = STRING_LITERALS.FK_EQMS_HR_TRAINING_ATTENDEE_ID;
export const FK_EQMS_HR_SKILL_MASTER_ID = STRING_LITERALS.FK_EQMS_HR_SKILL_MASTER_ID;
export const FK_EQMS_HR_REQUIRED_SKILL_LEVEL_ID = STRING_LITERALS.FK_EQMS_HR_REQUIRED_SKILL_LEVEL_ID;
export const FK_EQMS_HR_ACQUIRED_SKILL_LEVEL_ID = STRING_LITERALS.FK_EQMS_HR_ACQUIRED_SKILL_LEVEL_ID;
export const METHOD_OF_EVALUATION_FIELD = STRING_LITERALS.METHOD_OF_EVALUATION_FIELD;
export const REMARKS_FIELD = STRING_LITERALS.REMARKS_FIELD;
export const ADDITIONAL_CONTROLS_COMMENT = STRING_LITERALS.ADDITIONAL_CONTROLS_COMMENT;
export const HIDDEN_INPUTS_COMMENT = STRING_LITERALS.HIDDEN_INPUTS_COMMENT;
export const EDIT_ID_PATTERN = STRING_LITERALS.EDIT_ID_PATTERN;
export const ROW_ID_PATTERN = STRING_LITERALS.ROW_ID_PATTERN;
export const SKILL_ROW_ID_PATTERN = STRING_LITERALS.SKILL_ROW_ID_PATTERN;
export const HIDDEN_INPUT_KEY_PATTERN = STRING_LITERALS.HIDDEN_INPUT_KEY_PATTERN;
export const CELL_KEY_PATTERN = STRING_LITERALS.CELL_KEY_PATTERN;

// Element types
export const ELEMENT_TYPE_HIDDEN = 'hidden';
export const ELEMENT_TYPE_NUMBER = 'number';
export const ELEMENT_TYPE_STRING = 'string';
export const ELEMENT_TYPE_DIV = 'div';

export const TABLE_EMPLOYEE_TRAINING_EVALUATION_SUPPORTING_FILES = 'eqms_hr_employee_training_evaluation_supporting_files';
export const COLUMN_FK_EQMS_FILE_ID = 'fk_eqms_file_id';

export const DIALOG_DELETE = 'delete';

export const UPDATE = 'update';
export const SKILL_LEVEL = 'skill_level';
export const SKILL_LEVEL_ID = 'skill_level_id';

export const STATUS_LABELS = {
  VALID: STRING_LITERALS.STATUS_VALID,
  INVALID: STRING_LITERALS.STATUS_INVALID,
};

export const MAGICSAVECONSTANT = {
  CREATE: STRING_LITERALS.CREATE,
  UPDATE: STRING_LITERALS.UPDATE,
  INSERT: STRING_LITERALS.INSERT,
  RESPONSE: STRING_LITERALS.RESPONSE,
  STATUS: STRING_LITERALS.STATUS_FIELD,
  ACTIVE: NUMBERMAP.ONE,
  INACTIVE: NUMBERMAP.ZERO,
  PATH: STRING_LITERALS.PATH,
  DATE_FORMAT: STRING_LITERALS.DATE_FORMAT,
  TRUE: STRING_LITERALS.TRUE,
  FAILED: STRING_LITERALS.FAILED,
  SUCCESS: STRING_LITERALS.SUCCESS,
  DATA_SOURCE_NAMES: {
    TRAINING_EVALUATION: STRING_LITERALS.EQMS_HR_TRAINING_EVALUATION,
    EMPLOYEE_TRAINING_EVALUATION: STRING_LITERALS.EQMS_HR_EMPLOYEE_TRAINING_EVALUATION,
  },
  DATA_FIELD_NAMES: {
    HR_TRAINING_EVALUATION: STRING_LITERALS.EQMS_HR_TRAINING_EVALUATION,
    HR_TRAINING_EVALUATION_ID: STRING_LITERALS.FK_EQMS_HR_TRAINING_EVALUATION_ID,
    TRAINING_SCHEDULE_ID: STRING_LITERALS.FK_EQMS_HR_TRAINING_SCHEDULE_ID,
    EVALUATION_DATE: STRING_LITERALS.EVALUATION_DATE_CONST,
    HR_EMPLOYEE_TRAINING_EVALUTION: STRING_LITERALS.EQMS_HR_EMPLOYEE_TRAINING_EVALUATION,
    HR_TRAINING_ATTENDEE_ID: STRING_LITERALS.FK_EQMS_HR_TRAINING_ATTENDEE_ID_FIELD,
    HR_SKILL_MASTER_ID: STRING_LITERALS.FK_EQMS_HR_SKILL_MASTER_ID_FIELD,
    REQUIRED_SKILL_LEVEL_ID: STRING_LITERALS.FK_EQMS_HR_REQUIRED_SKILL_LEVEL_ID_FIELD,
    ACQUIRED_SKILL_LEVEL_ID: STRING_LITERALS.FK_EQMS_HR_ACQUIRED_SKILL_LEVEL_ID_FIELD,
    METHOD_OF_EVALUATION: STRING_LITERALS.METHOD_OF_EVALUATION_FIELD_NAME,
    REMARK: STRING_LITERALS.REMARK_FIELD,
    STATUS: STRING_LITERALS.STATUS_FIELD,
    ACTIVE: NUMBERMAP.ONE,
    INACTIVE: NUMBERMAP.ZERO,
  },
};

export const DISPLAY_DATE_FORMAT = 'YYYY-MM-DD';

// Table header constants
export const TABLE_HEADER_SNO = STRING_LITERALS.TABLE_HEADER_SNO;
export const TABLE_HEADER_NAME = STRING_LITERALS.TABLE_HEADER_NAME;
export const TABLE_HEADER_ROLE = STRING_LITERALS.TABLE_HEADER_ROLE;
export const TABLE_HEADER_DEPARTMENT = STRING_LITERALS.TABLE_HEADER_DEPARTMENT;
export const TABLE_HEADER_STATUS = STRING_LITERALS.TABLE_HEADER_STATUS;
export const NO_RECORD_FOUND = STRING_LITERALS.NO_RECORD_FOUND;
export const TABLE_HEADER_EVALUATION_DETAILS = STRING_LITERALS.TABLE_HEADER_EVALUATION_DETAILS;

export const TRAINING_EVALUATION_ERROR_MESSAGES = {
  TITLE_OF_TRAINING: 'Title of Training is required',
  DATE_OF_EVALUATION: 'Date of Evaluation is required',
}

export const TRAINING_EVALUATION_ERROR = {
  UNHANDLED_ERROR_TITLE: 'Something Went Wrong',
  VISIT_HOME_BUTTON: 'Visit Home Page',
  ICON: 'error',
  CUSTOM_ALERT: 'customAlert',
};